services:
  db:
    image: postgres:15

    container_name: scrapper-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: scrapper
    expose: 
    - "5432"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend   # usa el Dockerfile dentro de backend
    container_name: scrapper-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
    - ./backend:/code

volumes:
  db_data:
  