// Lista de cartas con id, title y tags abundantes

export const cardsData = [
    {
        id: "card-1",
        title: "Clientes Corporativos",
        tags: [
            "Profesional",
            "B2B",
            "Empresas",
            "Grandes",
            "Contratos",
            "Descuentos",
            "Facturación",
            "Crédito",
            "Suscripción",
            "Soporte Premium",
        ],
    },
    {
        id: "card-2",
        title: "Clientes Minoristas",
        tags: [
            "Consumidor",
            "B2C",
            "Individual",
            "Compras puntuales",
            "Efectivo",
            "Tarjeta",
            "PayPal",
            "Transferencia",
            "Cambios frecuentes",
            "Ofertas especiales",
        ],
    },
    {
        id: "card-3",
        title: "Clientes Premium",
        tags: [
            "VIP",
            "Exclusivo",
            "Alto valor",
            "Atención dedicada",
            "Beneficios especiales",
            "Prioridad",
            "Acceso temprano",
            "Descuentos máximos",
            "Garantía extendida",
            "Asesor personal",
        ],
    },
    {
        id: "card-4",
        title: "Productos Electrónicos",
        tags: [
            "Tecnología",
            "Gadgets",
            "Computadoras",
            "Móviles",
            "Accesorios",
            "Garantía",
            "Importado",
            "Local",
            "Stock disponible",
            "Envío rápido",
        ],
    },
    {
        id: "card-5",
        title: "Ropa y Accesorios",
        tags: [
            "Moda",
            "Vestimenta",
            "Zapatos",
            "Bolsas",
            "Joyas",
            "Temporada",
            "Tendencia",
            "Diseñador",
            "Talla única",
            "Colección nueva",
        ],
    },
    {
        id: "card-6",
        title: "Alimentos y Bebidas",
        tags: [
            "Orgánico",
            "Fresco",
            "Bebidas",
            "Snacks",
            "Lácteos",
            "Carbohidratos",
            "Proteína",
            "Gluten-free",
            "Vegano",
            "Importado",
        ],
    },
    {
        id: "card-7",
        title: "Hogar y Decoración",
        tags: [
            "Muebles",
            "Decoración",
            "Textiles",
            "Iluminación",
            "Organización",
            "Cocina",
            "Baño",
            "Dormitorio",
            "Sala",
            "Exterior",
        ],
    },
    {
        id: "card-8",
        title: "Pedidos Pendientes",
        tags: [
            "Sin procesar",
            "En revisión",
            "Pendiente pago",
            "Requiere confirmación",
            "Stock verificar",
            "Dirección incompleta",
            "No contactado",
            "Esperando aprobación",
            "En cola",
            "Prioridad baja",
        ],
    },
    {
        id: "card-9",
        title: "Pedidos en Preparación",
        tags: [
            "Empacando",
            "En almacén",
            "Recogiendo stock",
            "Etiquetando",
            "Control de calidad",
            "Verificación final",
            "Listo para envío",
            "Esperando transportista",
            "En proceso",
            "Pronto listo",
        ],
    },
    {
        id: "card-10",
        title: "Pedidos en Tránsito",
        tags: [
            "Enviado",
            "En camino",
            "Rastreable",
            "Local",
            "Nacional",
            "Internacional",
            "Entrega estimada",
            "En aduana",
            "Trasbordo",
            "Próximo seguimiento",
        ],
    },
    {
        id: "card-11",
        title: "Pedidos Entregados",
        tags: [
            "Completado",
            "Recibido",
            "Confirmado",
            "Satisfecho",
            "Pendiente reseña",
            "Reseña dada",
            "Garantía activa",
            "Período retorno",
            "Finalmente procesado",
            "Archivo histórico",
        ],
    },
    {
        id: "card-12",
        title: "Pedidos Cancelados",
        tags: [
            "Cancelado cliente",
            "Stock agotado",
            "Reembolso procesado",
            "Sin respuesta",
            "Cambio de idea",
            "Duplicado",
            "Error usuario",
            "Precio modificado",
            "Promoción terminada",
            "Archivado",
        ],
    },
    {
        id: "card-13",
        title: "Stock Alto",
        tags: [
            "Disponible",
            "Abundante",
            "Suficiente",
            "Rotación normal",
            "Sin riesgo",
            "Almacenado",
            "Listo venta",
            "No urgente",
            "Seguridad OK",
            "Óptimo",
        ],
    },
    {
        id: "card-14",
        title: "Stock Medio",
        tags: [
            "Moderado",
            "Vigilancia recomendada",
            "Monitor regular",
            "Pedido pronto",
            "Sin prisa",
            "Estable",
            "Normal",
            "Bajo riesgo",
            "Próximo descuento",
            "Atención básica",
        ],
    },
    {
        id: "card-15",
        title: "Stock Bajo",
        tags: [
            "Crítico",
            "Urgente reorden",
            "Peligro agotamiento",
            "Activar alerta",
            "Acelerar entrega",
            "Comunicar clientes",
            "Preparar sustituto",
            "Negociar proveedor",
            "Alto riesgo",
            "Acción inmediata",
        ],
    },
];

export default cardsData;
